# Generated by Django 3.2.9 on 2021-11-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RuneWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('effect', models.TextField()),
                ('weapons', models.CharField(db_index=True, max_length=255)),
                ('char_level', models.IntegerField()),
                ('runes', models.ManyToManyField(db_index=True, to='runewords.Rune')),
            ],
        ),
    ]
